variables:
  - group: 'Devops Automation'


trigger:
  branches:
    include:
    - main


stages:
- stage: 'Git_and_Dependencies'
  condition: |
    and(
      ne(variables['Build.SourceBranch'], 'refs/heads/releases'),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  jobs:
  - job: 'onPushJob'
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
    - script: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    - script: env | sort
      displayName: 'Environment / Context'
    - checkout: self
      path: Databricks
      persistCredentials: "true"
      clean: "true"
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'
    - script: databricks fs cp =$(Build.SourcesDirectory)/$(Build.Repository.Name)/Databricks/dist/dab_whl-0.0.1-py3-none-any.whl dbfs:/Volumes/sales_dbt/sales_kiran_sreekumar/wheel --overwrite
      displayName: 'Copy to volumes'


- stage: 'Databricks_Asset_Bundles_Deployment'
  displayName: 'Deploying Bundles'
  jobs:
  - job: 'bundle_deploy'
    steps:

    - script: |
            databricks bundle deploy --var="warehouse_id=$(BUNDLE_VAR_warehouse_id),node_type=$(BUNDLE_VAR_node_type)"
      displayName: 'Deploying Bundles'

    




