variables:
  - group: 'Devops Automation'

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - 'azure-pipelines-testcase.yml'   


jobs:
  - job: UnitTests
    displayName: 'Unit Tests'
    # Trigger unit test upon making a PR against the /ref/head/main branch
    condition: |
      and(
        not(eq(variables['Build.Reason'], 'IndividualCI')),
        eq(variables['Build.Reason'], 'PullRequest'),
        eq(variables['System.PullRequest.TargetBranch'], 'main')
      )
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'

    - checkout: self
      persistCredentials: true
      clean: true
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'

    - task: UsePythonVersion@0
      displayName: 'Use Python 3.8'
      inputs:
        versionSpec: 3.10.x


    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
      displayName: 'Install dependencies'

    - script: |
        pytest --junitxml=$(Build.StagingDirectory)/test.xml
      workingDirectory: 'src'
      displayName: 'Run unit tests with pytest'

