variables:
  - group: 'Devops Automation'

pr:
  branches:
    include:
    - main

stages:
- stage: 'Git_and_Dependencies'
  condition: |
    and(
      ne(variables['Build.SourceBranch'], 'refs/heads/releases'),
      not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
    )
  jobs:
  - job: 'onPushJob'
    pool:
      vmImage: 'ubuntu-20.04'

    steps:
    - script: env | sort
      displayName: 'Environment / Context'
    - checkout: self
      persistCredentials: "true"
      clean: "true"
      displayName: 'Checkout & Build.Reason: $(Build.Reason) & Build.SourceBranchName: $(Build.SourceBranchName)'





- stage: 'Terraform_Deploy'
  displayName: 'Terraform Config Validation'
  jobs:
  - job: 'Terraform_Validate'
    workspace:
      clean: all
    steps:
    - script: |
            terraform -chdir=terraform/modules/workflows/ init
            terraform -chdir=terraform/modules/workflows/  validate
            terraform -chdir=terraform/modules/workflows/  plan 
            terraform -chdir=terraform/modules/workflows/  apply -auto-approve
      workingDirectory: "$(Build.SourcesDirectory)"

      